apiVersion: v1
kind: Namespace
metadata:
  name: actions-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  namespace: actions-namespace
  labels:
    test: release-v0.0.4
spec:
  selector:
    matchLabels:
      app: app-1
  replicas: 2
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: app-1
          image: greghint/cloudsat
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-1
  namespace: actions-namespace
spec:
  selector:
    app: app-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app-1
  namespace: actions-namespace
spec:
  to:
    kind: Service
    name: app-1
  port:
    targetPort: 8080
